[build]
  base = "/"
  publish = "dist"  # or "build" depending on your setup
  command = "npm run build"
  functions = "netlify/functions"  # Define where your functions are located

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true